"use client";

import { useState } from "react";
import Link from "next/link";
import { useCart } from "@/context/cart-context";
import { formatINR } from "@/lib/calculations";
import { Icon } from "@/components/icons";

export default function CheckoutPage() {
  const { items, subtotal } = useCart();
  const [step, setStep] = useState(0);
  const total = subtotal * 1.18 + (subtotal >= 5000 ? 0 : 299);
  if (!items.length) return <section className="section"><div className="narrow empty-cart"><Icon name="cart" size={50} /><h2>No items to checkout</h2><Link className="button button-primary" href="/wallpapers">Shop wallpapers</Link></div></section>;
  return <><section className="page-hero"><div className="container"><span className="eyebrow">Secure checkout</span><h1>Complete your order.</h1><p>Address, serviceability and payment are separated into mobile-friendly steps.</p></div></section><section className="section"><div className="narrow"><div className="studio-shell" style={{ gridTemplateColumns: "190px 1fr", minHeight: 560 }}><aside className="studio-sidebar"><h3>Checkout</h3><div className="studio-steps">{["Contact", "Address", "Installation", "Payment"].map((label,index)=><div key={label} className={`studio-step ${index===step?"active":index<step?"done":""}`}><b>{index<step?<Icon name="check" size={13}/>:index+1}</b><span>{label}</span></div>)}</div></aside><div className="studio-content"><div className="studio-panel">
    {step===0&&<><span className="eyebrow">Customer information</span><h2>How can we reach you?</h2><div className="form-grid" style={{marginTop:20}}><label><span>Full name</span><input placeholder="Customer name"/></label><label><span>Mobile number</span><input inputMode="tel" placeholder="+91"/></label><label style={{gridColumn:"1/-1"}}><span>Email address</span><input type="email" placeholder="email@example.com"/></label></div></>}
    {step===1&&<><span className="eyebrow">Delivery address</span><h2>Where should we deliver?</h2><div className="form-grid" style={{marginTop:20}}><label style={{gridColumn:"1/-1"}}><span>Full address</span><input placeholder="House, street and landmark"/></label><label><span>City</span><input placeholder="Agra"/></label><label><span>PIN code</span><input inputMode="numeric" placeholder="282001"/></label><label><span>State</span><input placeholder="Uttar Pradesh"/></label></div></>}
    {step===2&&<><span className="eyebrow">Installation</span><h2>Do you need professional installation?</h2><div className="choice-grid" style={{gridTemplateColumns:"1fr 1fr"}}><button className="choice-card selected"><Icon name="check"/><strong>Add installation</strong><small>Serviceability and final rate confirmed after PIN-code check.</small></button><button className="choice-card"><Icon name="home"/><strong>Product only</strong><small>I will arrange installation separately.</small></button></div></>}
    {step===3&&<><span className="eyebrow">Payment</span><h2>Choose a payment method</h2><div className="choice-grid" style={{gridTemplateColumns:"1fr 1fr"}}><button className="choice-card selected"><Icon name="shield"/><strong>UPI / Card / Netbanking</strong><small>Razorpay order creation and webhook verification ready to connect.</small></button><button className="choice-card"><Icon name="truck"/><strong>Cash on Delivery</strong><small>Available for eligible ready-roll orders.</small></button><button className="choice-card"><Icon name="calculator"/><strong>Bank transfer</strong><small>Useful for commercial quotations and bulk orders.</small></button><button className="choice-card"><Icon name="wand"/><strong>50% advance</strong><small>Recommended for custom printed wallpaper.</small></button></div><div className="price-summary" style={{marginTop:20}}><div><span>Items</span><b>{items.length}</b></div><div><span>Payable estimate</span><b>{formatINR(total)}</b></div></div></>}
    </div><div className="studio-footer"><button className="button button-outline" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</button>{step<3?<button className="button button-primary" onClick={()=>setStep(step+1)}>Continue <Icon name="arrow" size={18}/></button>:<button className="button button-dark" onClick={()=>alert("Demo checkout complete. Connect Razorpay and Supabase environment variables for live payments.")}>Place demo order</button>}</div></div></div></div></section></>;
}
